<?php

/**
 * This file was generated by Drago Generator.
 */

declare(strict_types=1);

namespace App\Core\User;

use Drago\Database\Entity;


/**
 * Class representing the user entity in the database.
 * Stores information about the user account, including username, email, password, and token.
 */
class UserEntity extends Entity
{
	public const string
		Table = 'users',
		ColumnId = 'id',
		ColumnUsername = 'username',
		ColumnEmail = 'email',
		ColumnPassword = 'password',
		ColumnToken = 'token';

	public int $id;
	public string $username;
	public string $email;
	public string $password;
	public string $token;
}
